---
name: Check links in README

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: /github/workspace/README.md --allow-dupe --allow-timeout --allow 202,429,500,501,502,503,504,509,521 --allow-redirect --request-delay 1 --white-list https://github,https://img.shields.io
