-- Enable GitHub Copilot for additional filetypes
vim.g.copilot_filetypes = {
    xml = true,
    html = true,
    css = true,
    javascript = true,
    typescript = true,
    javascriptreact = true,
    typescriptreact = true,
    python = true,
    lua = true,
    go = true,
    rust = true,
    ruby = true,
    php = true,
    java = true,
    c = true,
    cpp = true,
    dart = true,
    kotlin = true,
    scala = true,
    swift = true,
    csharp = true,
    fsharp = true,
    vb = true,
    haskell = true,
    ocaml = true,
    elixir = true,
    clojure = true,
    erlang = true,
    sql = true,
    yaml = true,
    json = true,
    markdown = true,
    tex = true,
    vim = true,
    sh = true,
    fish = true,
    zsh = true,
    bash = true,
    shell = true,
    dockerfile = true,
    makefile = true,
    cmake = true,
    plaintext = true,
    gitcommit = true,
    gitconfig = true,
    gitrebase = true,
    gitignore = true,
    git = true,
    nix = true,
    -- Add more filetypes as needed
}

vim.g.copilot_no_tab_map = true
-- require('copilot').setup({})
