---
- name: Execute Install Missing Dependencies
  shell: bash scripts/debian_install.sh
  when: ansible_pkg_mgr == 'apt'
  become: yes

- name: Install OS-specific packages on Debian-based systems (Ubuntu)
  apt:
    name:
      - 'zsh'
      - 'tmux'
      - 'fzf'
      - 'bat'
      - 'exa'
      - 'fd-find'
      - 'ripgrep'
      - 'bpytop'
    state: present
  when: ansible_pkg_mgr == 'apt'
  become: yes

- name: Install OS-specific packages on Red Hat-based systems (Amazon Linux)
  yum:
    name:
      - 'zsh'
      - 'tmux'
      - 'fzf'
      - 'lazygit'
      - 'bat'
      - 'exa'
      - 'fd-find'
      - 'ripgrep'
      - 'ansible'
      - 'lsd'
      - 'fastfetch'
      - 'bpytop'
    state: present
  when: ansible_pkg_mgr == 'yum'
  become: yes

- name: Install OS-specific packages on Arch Linux
  pacman:
    name:
      - 'neovim'
      - 'zsh'
      - 'fzf'
      - 'tmux'
      - 'bpytop'
      - 'lsd'
      - 'fastfetch'
      - 'ansible'
      - 'bat'
      - 'exa'
      - 'fd'
      - 'ripgrep'
      - 'lazygit'
    state: present
  when: ansible_pkg_mgr == 'pacman'
  become: yes

# tasks file for ansible.archyay
- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "$HOME/yay"
    update: true

- name: Build and install yay
  command:
    chdir: "$HOME/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay

- name: Install OS-specific packages on macOS using Homebrew
  homebrew:
    name:
      - 'neovim'
      - 'zsh'
      - 'fzf'
      - 'tmux'
      - 'bpytop'
      - 'lsd'
      - 'fastfetch'
      - 'ansible'
      - 'bat'
      - 'exa'
      - 'fd'
      - 'ripgrep'
      - 'lazygit'
    state: present
  when: ansible_pkg_mgr == 'homebrew'
  become: yes

