---
- name: Install OS-specific packages
  become: yes
  hosts: localhost
  gather_facts: yes
  tasks:
  - name: Install OS-specific packages on Debian-based systems (Ubuntu)
    apt:
      name: ['fzf', 'bat', 'exa', 'fd-find', 'ripgrep', 'ansible', 'bpytop'] 
      state: present
    with_items:
      - fzf
      - bat
      - exa
      - fd-find
      - ripgrep
      - ansible
      - bpytop
    # when system is using apt
    when: ansible_pkg_mgr == 'apt' 
    become: yes

  - name: Execute Install Missing Dependencies
    shell: bash scripts/debian_install.sh 
    when: ansible_pkg_mgr == 'apt' 
    become: yes

  - name: Install OS-specific packages on Red Hat-based systems (Amazon Linux)
    yum:
      name: ['zsh', 'tmux', 'fzf', 'lazygit', 'bat', 'exa', 'fd-find', 'ripgrep', 'ansible', 'lsd', 'fastfetch', 'bpytop'] 
      state: present
    with_items:
      - zsh
      - tmux
      - fzf
      - lazygit
      - bat
      - exa
      - fd-find
      - ripgrep
      - ansible
      - lsd
      - fastfetch
      - bpytop
    when: ansible_pkg_mgr == 'yum'
    become: yes

  - name: Install OS-specific packages on Arch Linux
    pacman:
      name: ['neovim', 'zsh', 'fzf', 'tmux', 'bpytop', 'lsd', 'fastfetch', 'ansible', 'bat', 'exa', 'fd', 'ripgrep', 'lazygit'] 
      state: present
    with_items:
      - neovim
      - zsh
      - fzf
      - tmux
      - bpytop
      - lsd
      - fastfetch
      - ansible
      - bat
      - exa
      - fd
      - ripgrep
      - lazygit
    when: ansible_pkg_mgr == 'pacman'
    become: yes

  - name: Install OS-specific packages on macOS using Homebrew
    homebrew:
      name: ['neovim', 'zsh', 'fzf', 'tmux', 'bpytop', 'lsd', 'fastfetch', 'ansible', 'bat', 'exa', 'fd', 'ripgrep', 'lazygit'] 
    with_items:
      - neovim
      - zsh
      - fzf
      - tmux
      - bpytop
      - lsd
      - fastfetch
      - ansible
      - bat
      - exa
      - fd
      - ripgrep
      - lazygit
    when: ansible_pkg_mgr == 'homebrew' 
