---
- name: Install OS-specific packages
  become: yes
  vars:
    OS: "{{ OS | default('') }}"
  hosts: localhost
  tasks:
  - name: Install OS-specific packages on Debian-based systems (Ubuntu)
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - fzf
      - lazygit
      - bat
      - exa
      - fd-find
      - ripgrep
      - ansible
      - lsd
      - bpytop
    when: OS == 'Linux' and ansible_distribution == 'Ubuntu'
    become: yes

  - name: Install OS-specific packages on Red Hat-based systems (Amazon Linux)
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - zsh
      - tmux
      - fzf
      - lazygit
      - bat
      - exa
      - fd-find
      - ripgrep
      - ansible
      - lsd
      - fastfetch
      - bpytop
    when: OS == 'Linux' and ansible_distribution == 'Amazon'
    become: yes

  - name: Install OS-specific packages on Arch Linux
    pacman:
      name: "{{ item }}"
      state: present
    with_items:
      - neovim
      - zsh
      - fzf
      - tmux
      - bpytop
      - lsd
      - fastfetch
      - ansible
      - bat
      - exa
      - fd
      - ripgrep
      - lazygit
    when: OS == 'Linux' and ansible_distribution == 'Arch'
    become: yes

  - name: Install OS-specific packages on macOS using Homebrew
    homebrew_installed:
      name: "{{ item }}"
    with_items:
      - neovim
      - zsh
      - fzf
      - tmux
      - bpytop
      - lsd
      - fastfetch
      - ansible
      - bat
      - exa
      - fd
      - ripgrep
      - lazygit
    when: OS == 'Darwin'
    register: brew_check
  
  - name: Install OS-specific packages on macOS using Homebrew
    homebrew:
      name: "{{ item }}"
    with_items:
      - neovim
      - zsh
      - fzf
      - tmux
      - bpytop
      - lsd
      - fastfetch
      - ansible
      - bat
      - exa
      - fd
      - ripgrep
      - lazygit
    when: OS == 'Darwin' and brew_check.changed
