---
- name: Cleanup Dotfiles
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Execute Install Missing Dependencies
      shell: bash scripts/backup_and_link.sh
      become: yes

