---
- name: Print current working directory
  command: "pwd"
  args:
    chdir: "{{ playbook_dir | dirname }}"
  register: pwd_output

- name: Debug pwd output
  debug:
    var: pwd_output.stdout_lines

- name: Link dotfiles
  command: "stow -t  $HOME -R dotfiles"
  args:
    chdir: "{{ playbook_dir | dirname }}"
  become: no

- name: Clone zsh-autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Clone zsh-syntax-highlighting plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Clone fzf-zsh-plugin plugin
  git:
    repo: https://github.com/Aloxaf/fzf-tab.git
    dest: ~/.oh-my-zsh/custom/plugins/fzf-tab


- name: Clone powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
