---
- name: Setup Dotfiles using Stow
  hosts: localhost
  become: yes

  tasks:
    - name: Ensure stow is installed
      package:
        name: stow
        state: present

    - name: Create symbolic links for dotfiles
      command: "stow -t {{ ansible_user_dir }} -d {{ playbook_dir }}/dotfiles -S {{ item }}"
      with_items:
        - "{{ query('fileglob', playbook_dir + '/dotfiles/*') | map('basename') }}"
        - "{{ query('fileglob', playbook_dir + '/dotfiles/.[^.]*') | map('basename') }}"

    - name: Create symbolic links for hidden directories in dotfiles
      command: "stow -t {{ ansible_user_dir }} -d {{ playbook_dir }}/dotfiles -S {{ item }}"
      with_items: "{{ query('fileglob', playbook_dir + '/dotfiles/.[^.]*') | map('basename') | reject('match', '^\.$') }}"

    - name: Create symbolic links for directories in .config
      command: "stow -t {{ ansible_user_dir }}/.config -d {{ playbook_dir }}/dotfiles/.config -S {{ item }}"
      with_items: "{{ query('fileglob', playbook_dir + '/dotfiles/.config/*') | map('basename') }}"

    - name: Create symbolic links for hidden directories in .config
      command: "stow -t {{ ansible_user_dir }}/.config -d {{ playbook_dir }}/dotfiles/.config -S {{ item }}"
      with_items: "{{ query('fileglob', playbook_dir + '/dotfiles/.config/.[^.]*') | map('basename') | reject('match', '^\.$') }}"

  post_tasks:
    - name: Print completion message
      debug:
        msg: "Dotfiles setup completed successfully!"

