---
- name: Setup Dotfiles
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Install stow package
      package:
        name: stow
        state: present

    - name: Set the base directory
      set_fact:
        base_dir: "{{ playbook_dir }}"
        parent_dir: "{{ playbook_dir | dirname }}"

    - name: Backup and link dotfiles
      command: "{{ item }}"
      become_user: ray  # Set the target user here
      args:
        chdir: "{{ parent_dir }}/dotfiles"  # Set the correct stow directory
      loop:
        - "stow -t $HOME -R *"
        - "stow -t $HOME -R .*"
        - "stow -t $HOME/.config -R *"

