---
- name: Cleanup Dotfiles
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Set the base directory
      set_fact:
        base_dir: "{{ playbook_dir }}"

    - name: Delete linked dotfiles
      command: "stow -t {{ ansible_env.HOME }} -D dotfiles"

