---
- name: Setup Terminal Environment
  hosts: localhost
  become: yes
  gather_facts: yes
  tasks:
  - name: Display menu
    pause:
      prompt: "Choose the tasks to execute (comma-separated): install_os_packages, install_miniconda, install_neovim, setup_dotfiles"
    register: user_selection

  - name: Execute selected tasks
    include_tasks: "{{ item }}.yml"
    loop: "{{ user_selection.user_input.split(',') }}"
    when: user_selection.user_input.split(',') | intersect(['install_os_packages', 'install_miniconda', 'install_neovim', 'setup_dotfiles']) | length > 0

