---
- name: Set up dotfiles
  hosts: localhost
  gather_facts: no
  become: yes

  tasks:
    - name: Execute dotfiles setup script
      shell: /bin/zsh ansible/scripts/backup_and_link.sh
    - name: Install Zsh
      package:
        name: zsh
        state: present

    - name: Set Zsh as default shell
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /bin/zsh

    - name: Copy default Zsh configuration files
      ansible.builtin.copy:
        src: /etc/skel/.zshrc
        dest: "{{ lookup('env', 'HOME') }}/.zshrc"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: '0644'
      notify: Restart Zsh

  handlers:
    - name: Restart Zsh
      ansible.builtin.shell:
        cmd: su - "{{ lookup('env', 'USER') }}" -c "exec zsh"

