---
- name: Set up dotfiles
  hosts: localhost
  gather_facts: no
  become: yes

  tasks:
    - name: Execute dotfiles setup script
      script: "{{ playbook_dir }}/scripts/backup_and_link.sh" 
    - name: Install Zsh
      package:
        name: zsh
        state: present

    - name: Set Zsh as default shell
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /bin/zsh

    - name: Set Zsh as default shell for current user
      shell: chsh -s /bin/zsh "{{ lookup('env', 'USER') }}"
