---
- name: Setup Terminal Environment
  become: yes
  gather_facts: yes
  tasks:
  - name: Install OS-specific packages
    include_tasks: install_os_packages.yml

  - name: Install Miniconda
    include_tasks: install_miniconda.yml

  - name: Install Neovim
    include_tasks: install_neovim.yml

  - name: Restore Dotfiles
    include_tasks: setup_dotfiles.yml
