---
- name: Setup Dotfiles
  hosts: localhost
  gather_facts: true  
  become: true

  tasks:
    - name: Install stow package
      package:
        name: stow
        state: present

    - name: Set the base directory
      set_fact:
        base_dir: "{{ playbook_dir }}"

    - name: Backup and link dotfiles
      command: "{{ item }}"
      loop:
        - "stow -t {{ ansible_env.HOME }} -d {{ base_dir }}/dotfiles -R *"
        - "stow -t {{ ansible_env.HOME }} -d {{ base_dir }}/dotfiles -R .*"
        - "stow -t {{ ansible_env.HOME }} -d {{ base_dir }}/dotfiles/.config -R *"

